exclude: .*node_modules/.*
default_language_version:
  # force all unspecified python hooks to run python3
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: debug-statements
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-symlinks
      - id: check-merge-conflict
      - id: check-byte-order-marker
      - id: pretty-format-json
        args:
          - --autofix
          - --no-sort-keys
          - --indent
          - "4"
        pass_filenames: true
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
        args: [--config=./pyproject.toml]
  - repo: https://github.com/timothycrosley/isort
    rev: 5.9.3
    hooks:
      - id: isort
        name: Run isort to sort imports in Python files
        args: ["--profile", "black"]
        files: \.py$
  - repo: local
    hooks:
      - id: flake8
        name: Run flake8
        language: script
        entry: ./ci/pre_commit_flake8.sh
        files: \.py$
        pass_filenames: true
