template_path: iam-policy-base.yaml
parameters:
  PolicyNameSuffix: teslambda-policy
  PolicyJSON: |
    {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Action": "airflow:*",
                "Resource": "arn:aws:airflow:{{ var.region }}:{{ var.account_id }}:environment/*",
                "Effect": "Allow"
            },
            {
                "Action": "s3:*",
                "Resource": "*",
                "Effect": "Allow"
            },
            {
                "Action": "execute-api:Invoke",
                "Resource": "arn:aws:execute-api:*:*:*",
                "Effect": "Allow"
            },
            {
                "Action": [
                    "ssm:GetParameter",
                    "ssm:GetParameters"
                ],
                "Resource": "*",
                "Effect": "Allow"
            },
            {
                "Action": [
                    "logs:CreateLogGroup",
                    "logs:CreateLogStream",
                    "logs:DescribeLogGroups",
                    "logs:GetLogEvents",
                    "logs:GetLogGroupFields",
                    "logs:GetLogRecord",
                    "logs:GetQueryResults",
                    "logs:PutLogEvents"
                ],
                "Resource": [
                    "arn:aws:logs:{{ var.region }}:{{ var.account_id }}:log-group:airflow-*"
                ],
                "Effect": "Allow"
            },
            {
                "Action": [
                    "iam:GetPolicy",
                    "iam:GetPolicyVersion",
                    "iam:ListRoles",
                    "iam:PassRole",
                    "secretsmanager:*",
                    "glue:BatchGet*",
                    "glue:Get*",
                    "glue:List*",
                    "glue:StartJobRun"
                ],
                "Resource": "*",
                "Effect": "Allow"
            },
            {
                "Action": [
                    "sqs:ChangeMessageVisibility",
                    "sqs:DeleteMessage",
                    "sqs:GetQueueAttributes",
                    "sqs:GetQueueUrl",
                    "sqs:ReceiveMessage",
                    "sqs:SendMessage"
                ],
                "Resource": "arn:aws:sqs:{{ var.region }}:*:airflow-celery-*",
                "Effect": "Allow"
            }
        ]
    }
