template_path: lambda-scheduler-template.yaml
parameters:
  StackName: tes-lambda
  ProductDescription: Tesseract Lambda, invokes tesseract module
  Handler: index.handler
  FileName: code/tesseract-0.1.0.zip
  RunTimeEnvironment: python3.9
  CustomIAMRoleNameSuffix: tes-lambda-role
  S3CodeBucket: "gd-{{ var.team_name}}-{{ var.env_val }}-tesseract"
