template_path: iam-role-base.yaml
parameters:
  StackName: "tesseract-mwaa"
  AssumingServices:
    - airflow.amazonaws.com
    - airflow-env.amazonaws.com
  MoreManagedPolicyArns:
    - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
    - "arn:aws:iam::aws:policy/AmazonAthenaFullAccess"
    - "arn:aws:iam::aws:policy/AmazonElasticMapReduceFullAccess"
    - "arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess"
    - "arn:aws:iam::aws:policy/AWSLambda_FullAccess"
    - "arn:aws:iam::aws:policy/AmazonEC2FullAccess"
    - "arn:aws:iam::aws:policy/AWSLambdaInvocation-DynamoDB"
    - "arn:aws:iam::{{ var.account_id }}:policy/{{ var.team_name }}-custom-tesflow-policy"
