# This is a workflow to build/launch or rebuild given sceptre CF stack

name: Deploy Tesseract

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab, with stack path as argument
  workflow_dispatch:
    inputs:
      region:
        description: which region should Tesseract product be deployed to?
        required: true
        default: us-west-2
      deploy_env:
        description: Provide Git Environment to get deploy credentials from
        required: true
        default: tesseract
jobs:
  # This workflow contains a single job called "build-stack" to deploy Tesseract
  build-stack:
    name: Deploy Tesseract
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: ${{  github.event.inputs.deploy_env }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install sceptre
        run: |
          pip3 install sceptre
      # Configure AWS Credentials
      - name: Configuring Deploy user
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_SECRET_KEY }}
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          role-duration-seconds: 7200
          aws-region: ${{  github.event.inputs.region }}

      # deploy base artifacts
      - name: deploy base stack via sceptre
        id: deploy_base_stack
        run: |
          aws sts get-caller-identity
          cd infrastructure
          sh vars/var_generator.sh ${{  github.event.inputs.region }}
          echo "Deploying artifacts bucket"
          sceptre --var-file=vars/deployment_vars.yaml launch -y worker-artifacts/tesseract-s3.yaml
          echo "Deploying Tesflow Module"
          sceptre --var-file=vars/deployment_vars.yaml launch -y tesflow/tesflow-policy.yaml
          sceptre --var-file=vars/deployment_vars.yaml launch -y tesflow/tesflow-role.yaml
          sceptre --var-file=vars/deployment_vars.yaml launch -y tesflow/tesflow.yaml
          echo "Deploying notification channel"
          sceptre --var-file=vars/deployment_vars.yaml launch -y reporting/notification-sns.yaml

      # deploy code artifacts
      - name: deploy code files
        id: deploy_code
        run: |
          aws sts get-caller-identity
          environment_val=`aws ssm get-parameter --name /AdminParams/Team/Environment --query "Parameter.Value" --output text`
          team_name_val=`aws ssm get-parameter --name /AdminParams/Team/Name --query "Parameter.Value" --output text`
          bucket_name="gd-$team_name_val-$environment_val-tesseract"
          pip install poetry
          poetry --version
          echo $bucketname
          aws s3 cp infrastructure/vars/emrinit.sh s3://$bucket_name/
          cd infrastructure
          sh vars/var_generator.sh ${{  github.event.inputs.region }}
          cd ..
          echo "**** Deploying tesseract lambda"
          cd tesseract_lambda
          ls src/tesseract/wrappers/
          make clean
          make build
          aws s3 cp dist/*.zip s3://$bucket_name/code/
          echo "**** Deploying tesseract resolver"
          cd ../tesseract_athena_get_resolver
          make clean
          make build
          aws s3 cp dist/*.zip s3://$bucket_name/code/
          echo "**** Deploying tesseract dynamo worker"
          cd ../tesseract_dynamo_worker
          make clean
          make build
          aws s3 cp dist/*.zip s3://$bucket_name/code/
          cd ../tesseract_data
          make clean
          make build
          aws s3 cp dist/*.zip s3://$bucket_name/code/
          cd ../tesseract_connector
          make clean
          make build
          aws s3 cp dist/*.zip s3://$bucket_name/code/
          echo "**** Deploying tesflow worker assets"
          cd ../tesseract_lambda/src
          aws s3 cp tesseract/wrappers/ s3://$bucket_name/airflow_environment/dags/tesseract/wrappers/ --recursive
          cd ../../tesflow_artifacts
          aws s3 cp . s3://$bucket_name/airflow_environment/dags/ --recursive


      # deploy worker code
      - name: deploy worker
        id: deploy_worker
        run: |
          aws sts get-caller-identity
          environment_val=`aws ssm get-parameter --name /AdminParams/Team/Environment --query "Parameter.Value" --output text`
          team_name_val=`aws ssm get-parameter --name /AdminParams/Team/Name --query "Parameter.Value" --output text`
          bucket_name="gd-$team_name_val-$environment_val-tesseract"
          cd infrastructure
          sceptre --var-file=vars/deployment_vars.yaml launch -y worker-artifacts/lambda-custom-policy.yaml
          sceptre --var-file=vars/deployment_vars.yaml launch -y worker-artifacts/lambda-role.yaml
          sceptre --var-file=vars/deployment_vars.yaml launch -y worker-artifacts/tesseract-dyn-loader.yaml
          sceptre --var-file=vars/deployment_vars.yaml launch -y worker-artifacts/tesseract-dyn-loader1.yaml
          sceptre --var-file=vars/deployment_vars.yaml launch -y worker-artifacts/tes-athena-get-resolver.yaml
          sceptre --var-file=vars/deployment_vars.yaml launch -y worker-artifacts/tes-lambda.yaml
          sceptre --var-file=vars/deployment_vars.yaml launch -y worker-artifacts/tesseract-connector.yaml
          echo "**** Deploying tessync artifacts"
          sceptre --var-file=vars/deployment_vars.yaml launch -y tessync/sync-access-policy.yaml
          sceptre --var-file=vars/deployment_vars.yaml launch -y tessync/sync-access-role.yaml
          sceptre --var-file=vars/deployment_vars.yaml launch -y tessync/tesseract-sync-api.yaml
          echo "**** Updating connections"
          sceptre --var-file=vars/deployment_vars.yaml launch -y worker-artifacts/tesseract-data.yaml
          aws lambda invoke --function-name gd-$team_name_val-$environment_val-tesseract-data-runner --payload '{"a":"b"}' out
          export region_val=${{  github.event.inputs.region }}
          export env_val=$environment_val
          export team_name_val=$team_name_val
          export secret_id=${{ secrets.DEPLOY_SECRET_ID }}
          export role=${{ secrets.AWS_DEPLOY_ROLE }}
          python scripts/init_worker.py

      # Notify on slack
      # Always checkout - https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
      - name: Get GD version of rtCamp actions
        if: ${{ always() }}
        uses: actions/checkout@v2
        with:
          repository: gdcorp-action-public-forks/action-slack-notify
          token: ${{ secrets.CLOUD_CREDS_UPDATE_TKN }}
          path: slack-notify-action

      # Post following message on Job Success
      - name: Success Notifier
        if: ${{ success() }}
        uses: ./slack-notify-action
        env:
          SLACK_CHANNEL: tesseract-deployments
          SLACK_USERNAME: ahpBot
          SLACK_ICON_EMOJI: ':clapping:'
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: 'Tesseract launch/Update successful :highfive:'
          SLACK_WEBHOOK: ${{ secrets.SLACK_ALERTS }}
          SLACK_FOOTER: ahpBot GitHub notification

      # Post following message on Job Failure
      - name: Failure Notifier
        if: ${{ failure() }}
        uses: ./slack-notify-action
        env:
          SLACK_CHANNEL: tesseract-deployments
          SLACK_USERNAME: ahpBot
          SLACK_ICON_EMOJI: ':headbang:'
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: 'Tesseract launch/Update failed \n ${{steps.build_task.outputs.output}} '
          SLACK_WEBHOOK: ${{ secrets.SLACK_ALERTS }}
          SLACK_FOOTER: ahpBot GitHub notification

      # Post following message on Job Cancellation
      - name: Cancel Notifier
        if: ${{ cancelled() }}
        uses: ./slack-notify-action
        env:
          SLACK_CHANNEL: tesseract-deployments
          SLACK_USERNAME: ahpBot
          SLACK_ICON_EMOJI: ':depressed:'
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: 'Tesseract launch/Update cancelled :sad:'
          SLACK_WEBHOOK: ${{ secrets.SLACK_ALERTS }}
          SLACK_FOOTER: ahpBot GitHub notification
