# This is a workflow to build/launch or rebuild given sceptre CF stack

name: Deploy Tesseract

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab, with stack path as argument
  workflow_dispatch:
    inputs:
      region:
        description: which region should Tesseract product be deployed to?
        required: true
        default: us-west-2
      environment:
        description: Provide Git Environment to get deploy credentials from
        required: true
        default: tesseract
jobs:
  # This workflow contains a single job called "build-stack" to deploy Tesseract
  build-stack:
    name: Deploy Tesseract
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: ${{  github.event.inputs.environment }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install sceptre
        run: |
          pip3 install sceptre
      # Configure AWS Credentials
      - name: Configuring Deploy user
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_SECRET_KEY }}
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          role-duration-seconds: 3600
          aws-region: ${{  github.event.inputs.region }}

      # deploy base artifacts
      - name: deploy base stack via sceptre
        id: deploy_base_stack
        run: |
          aws sts get-caller-identity
          cd infrastructure
          sh vars/var_generator.sh ${{  github.event.inputs.region }}
          echo "Deploying Tesflow Module"

          echo "Deploying notification channel"
          echo "Deploying artifacts bucket"
          echo "Deploying worker artifacts"

      # deploy code artifacts
      - name: deploy code files
        id: deploy_code
        run: |
          aws sts get-caller-identity
          ls
          cat infrastructure/vars/deployment_vars.yaml
          environment_val=`aws ssm get-parameter --name /AdminParams/Team/Environment --query "Parameter.Value" --output text`
          team_name_val=`aws ssm get-parameter --name /AdminParams/Team/Name --query "Parameter.Value" --output text`
          bucket_name="gd-$team_name_val-$environment_val-tesseract"
          pip install poetry
          poetry --version
          echo $bucketname
          echo "**** Deploying tesseract lambda"
          cd tesseract_lambda
          make clean
          make build
          aws s3 cp dist/*.zip s3://$bucket_name/code/
          echo "**** Deploying tesseract resolver"
          cd ../tesseract_athena_get_resolver
          make clean
          make build
          aws s3 cp dist/*.zip s3://$bucket_name/code/
          echo "**** Deploying tesseract dynamo worker"
          cd ../dynamo_worker
          make clean
          make build
          aws s3 cp dist/*.zip s3://$bucket_name/code/




      # Notify on slack
      # Always checkout - https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
      - name: Get GD version of rtCamp actions
        if: ${{ always() }}
        uses: actions/checkout@v2
        with:
          repository: gdcorp-action-public-forks/action-slack-notify
          token: ${{ secrets.CLOUD_CREDS_UPDATE_TKN }}
          path: slack-notify-action

      # Post following message on Job Success
      - name: Success Notifier
        if: ${{ success() }}
        uses: ./slack-notify-action
        env:
          SLACK_CHANNEL: tesseract-deployments
          SLACK_USERNAME: ahpBot
          SLACK_ICON_EMOJI: ':clapping:'
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: 'Stack launch/Update successful for ${{  github.event.inputs.stack_path }} :highfive:'
          SLACK_WEBHOOK: ${{ secrets.SLACK_ALERTS }}
          SLACK_FOOTER: ahpBot GitHub notification

      # Post following message on Job Failure
      - name: Failure Notifier
        if: ${{ failure() }}
        uses: ./slack-notify-action
        env:
          SLACK_CHANNEL: tesseract-deployments
          SLACK_USERNAME: ahpBot
          SLACK_ICON_EMOJI: ':headbang:'
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: 'Stack launch/Update failed for ${{  github.event.inputs.stack_path }} \n ${{steps.build_task.outputs.output}} '
          SLACK_WEBHOOK: ${{ secrets.SLACK_ALERTS }}
          SLACK_FOOTER: ahpBot GitHub notification

      # Post following message on Job Cancellation
      - name: Cancel Notifier
        if: ${{ cancelled() }}
        uses: ./slack-notify-action
        env:
          SLACK_CHANNEL: tesseract-deployments
          SLACK_USERNAME: ahpBot
          SLACK_ICON_EMOJI: ':depressed:'
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: 'Stack launch/Update cancelled for ${{  github.event.inputs.stack_path }} :sad:'
          SLACK_WEBHOOK: ${{ secrets.SLACK_ALERTS }}
          SLACK_FOOTER: ahpBot GitHub notification
